### ISSUE TITLE
Нету проверки на то что вводится 

### ISSUE THREAD

**Issue by Muxamedin** [KaraivanOK/hillel#4]
Задача рабочая тогда когда вводятся только числа и падает когда введется что другое
 
https://github.com/KaraivanOK/hillel/blob/6cbe31bd92c8552cee1c0747efdc220600fead91/HW5/piramida_iz_chisel.py#L1
Тестовый пример :
![image](https://user-images.githubusercontent.com/4419752/128629728-5e82d31b-97af-4053-809a-add0d6a30c07.png)

См. задание: 
 >> Если не в диапазоне - сообщает о проблеме и заканчивает работу.
 >> Во всех задачах реализовать проверку правильности введения значений.

**Comment by KaraivanOK** [comment]
Реализовать приложение которое принимает на вход значение чисел от 3 до 9;Выполняет проверку на правильность введеного числа в указаном диапазоне.Если не в диапазоне - сообщает о проблеме и заканчивает работу.Иначе - печатает пирамиду из чисел.Если бы было сказано проверить на не число, как в второй задаче,я бы без проблем сделал. Отправлено из приложения "Почта" для Windows 10 От: Mikel BilyОтправлено: воскресенье, 8 августа 2021 г. в 14:03Кому: KaraivanOK/hillelКопия: SubscribedТема: [KaraivanOK/hillel] Нету проверки на то что вводится (#4) Задача рабочая тогда когда вводятся только числа и падает когда введется что другоеhttps://github.com/KaraivanOK/hillel/blob/6cbe31bd92c8552cee1c0747efdc220600fead91/HW5/piramida_iz_chisel.py#L1Тестовый пример :См. задание:Если не в диапазоне - сообщает о проблеме и заканчивает работу.Во всех задачах реализовать проверку правильности введения значений.—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Muxamedin** [comment]
Согласен ,
Закрываем тогда issue
