### ISSUE TITLE
Рекомендации к коду , что исправить

### ISSUE THREAD

**Issue by Muxamedin** [KaraivanOK/hillel#5]
Програма работает как ожидается 
Но:

Сообщение  в этой строке 
https://github.com/KaraivanOK/hillel/blob/6cbe31bd92c8552cee1c0747efdc220600fead91/HW5/game_ugadai_chislo.py#L28
печятается при отрицательных числах и при вводе строки 
см. пример 
![image](https://user-images.githubusercontent.com/4419752/128630179-db9ba130-4a0a-4b46-93f2-3dd775314bd8.png)

поэтому сообщение не соответствует действительности 
его можно изменить на  что то общее 
Пример:
"Вы ввели что то не то. Будьте внимательны ........" или что то в этом духе

**Comment by KaraivanOK** [comment]
Сейчас изменю, но это даёт вот эта строка:elif chislo_polzovatelya.isalnum() == False:  # Если строка не состоит только из цифр и букв, то засчитываем  Отправлено из приложения "Почта" для Windows 10 От: Mikel BilyОтправлено: воскресенье, 8 августа 2021 г. в 14:20Кому: KaraivanOK/hillelКопия: SubscribedТема: [KaraivanOK/hillel] Рекомендации к коду , что исправить (#5) Програма работает как ожидаетсяНо:Сообщение в этой строкеhttps://github.com/KaraivanOK/hillel/blob/6cbe31bd92c8552cee1c0747efdc220600fead91/HW5/game_ugadai_chislo.py#L28печятается при отрицательных числах и при вводе строкисм. примерпоэтому сообщение не соответствует действительностиего можно изменить на что то общееПример:"Вы ввели что то не то. Будьте внимательны ........" или что то в этом духе—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by KaraivanOK** [comment]
Так как оно воспринимает минус как не число и не букву. Отправлено из приложения "Почта" для Windows 10 От: Mikel BilyОтправлено: воскресенье, 8 августа 2021 г. в 14:20Кому: KaraivanOK/hillelКопия: SubscribedТема: [KaraivanOK/hillel] Рекомендации к коду , что исправить (#5) Програма работает как ожидаетсяНо:Сообщение в этой строкеhttps://github.com/KaraivanOK/hillel/blob/6cbe31bd92c8552cee1c0747efdc220600fead91/HW5/game_ugadai_chislo.py#L28печятается при отрицательных числах и при вводе строкисм. примерпоэтому сообщение не соответствует действительностиего можно изменить на что то общееПример:"Вы ввели что то не то. Будьте внимательны ........" или что то в этом духе—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
